name: react-app

on:
    push:
      branches: ['artifacts']

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test

    
      - name: uploading a single file
        uses: actions/upload-artifact@v4
        with:
            name: my-artifact
            path: echo.txt
    #   - name: Archive code coverage results
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: code-coverage-report
    #       path: output/test/code-coverage.html
