name: Node CI

on:
    push:
      branches: ['artifacts']
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust based on your project's requirements

      # Step 3: Install dependencies and fix vulnerabilities
      - name: Install and audit dependencies
        run: |
          npm install
          npm audit fix || echo "Audit fix completed with warnings"
          npm audit fix --force || echo "Force fix applied with potential breaking changes"
          npm install

      # Step 4: Build and run tests
      - name: Build and test application
        run: |
          npm run build --if-present
          npm test

      # Step 5: Archive production artifacts (excluding Markdown files)
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md

      # Step 6: Archive code coverage results
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html
