name: Build and Test React App

on:
  push:
    branches:
      - artifacts
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Update dependencies
        run: |
          npm install react-scripts@latest
          npm install webpack@latest

      - name: Build the React app
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm run build

      - name: Run tests
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm test
